export * from "./Footer"
export * from "./FAQs"
export * from "./BuyingStep"
export * from "./Hero"
export * from "./Features"
export * from "./Benefits"
export * from "./Gallery"
export * from "./Clients"
